package models

import (
	"time"
	"gorm.io/gorm"
)

type User struct {
	ID           string         `gorm:"primaryKey" json:"id"` // Use string ID for flexibility (e.g. Auth0 or UUID)
	Username     string         `gorm:"uniqueIndex;not null" json:"username"`
	PasswordHash string         `json:"-"`
	AvatarColor  string         `json:"avatarColor"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}

type Note struct {
	ID        string         `gorm:"primaryKey" json:"id"` // IDs generated by frontend or UUID
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`

	UserID      string `gorm:"index" json:"userId"`
	FolderID    string `gorm:"index" json:"folderId"`
	Title       string `json:"title"`
	Content     string `gorm:"type:text" json:"content"`
	
	// Sharing Configuration
	IsPublic         bool   `gorm:"default:false" json:"isPublic"`
	PublicPermission string `gorm:"default:'read'" json:"publicPermission"` // 'read' or 'edit'
}

type Folder struct {
	ID        string    `gorm:"primaryKey" json:"id"`
	UserID    string    `gorm:"index" json:"userId"`
	Name      string    `json:"name"`
	Icon      string    `json:"icon"`
	Type      string    `json:"type"` // 'user', 'trash', 'family'
	CreatedAt time.Time `json:"createdAt"`
}

type Collaborator struct {
	NoteID     string `gorm:"primaryKey" json:"noteId"`
	UserID     string `gorm:"primaryKey" json:"userId"`
	Permission string `json:"permission"` // 'read', 'edit', 'remove'
}
